version: '3'

services:
   autochek_location_service:
      build: ./
      ports:
         - '8082:8082'
      depends_on:
         - db
      environment:
         - DB_HOST=db
         - DB_PORT=5432
         - DB_USERNAME=postgres
         - DB_PASSWORD=postgres
         - DB_DATABASE=autochek

   db:
      image: postgres
      restart: always
      ports:
         - '5432:5432'
      environment:
         POSTGRES_PASSWORD: postgres
         POSTGRES_USER: postgres
         POSTGRES_DB: autochek

   nginx:
      image: nginx:latest
      ports:
         - '80:80'
      volumes:
         - ./default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
         - autochek_location_service
